<?php

// 该文件为权限列表，键必须为路由名字
return [
    "solution" => "查看任意用户提交的代码",
    "delete_discussion" => "将题目讨论删除",
    "top_discussion" => "将题目讨论置顶",
    "hidden_discussion" => "将题目讨论隐藏或公开",
    "contest.balloons" => "查看气球派送信息",
    "contest.deliver_ball" => "执行操作：派送气球",

    "admin.home" => "后台管理首页",
    "admin.cmd_polling" => "启动或关闭判题端",
    "admin.notice.list" => "查看公告列表",
    "admin.notice.add" => "添加公告",
    "admin.notice.update" => "修改公告",
    "admin.notice.delete" => "删除公告",
    "admin.notice.update_state" => "公开或隐藏公告",
    "admin.user.list" => "查看用户列表",
    "admin.user.privileges" => "查看权限分配表",
    "admin.user.create" => "创建用户",
    "admin.user.delete" => "删除用户",
    "admin.user.update_revise" => "修改用户可自行编辑资料的次数",
    "admin.user.privilege_create" => "给任意用户添加权限",
    "admin.user.privilege_delete" => "删除某用户的权限",
    "admin.user.reset_pwd" => "重置某用户的登录密码",
    "admin.user.blacklist" => "查看黑名单列表",
    "admin.user.blacklist_create" => "将某用户添加到黑名单",
    "admin.user.blacklist_delete" => "将某用户从黑名单中删除",
    "admin.problem.list" => "查看题目列表",
    "admin.problem.add" => "添加题目",
    "admin.problem.update_withId" => "修改题目",
    "admin.problem.update_hidden" => "公开或隐藏题目",
    "admin.problem.get_spj" => "查看某题目的spj特判程序源码",
    "admin.problem.tags" => "查看题目的标签列表",
    "admin.problem.tag_delete" => "删除某题目的标签",
    "admin.problem.tag_pool" => "管理标签池",
    "admin.problem.tag_pool_delete" => "删除标签池中的标签",
    "admin.problem.tag_pool_hidden" => "隐藏标签池中的标签",
    "admin.problem.test_data" => "查看题目的测试数据列表",
    "admin.problem.upload_data" => "向题目上传测试数据",
    "admin.problem.get_data" => "查看题目的测试数据内容",
    "admin.problem.update_data" => "修改题目的测试数据内容",
    "admin.problem.delete_data" => "删除题目的测试数据文件",
    "admin.problem.rejudge" => "重判用户提交",
    "admin.problem.import_export" => "进入题库导入导出界面",
    "admin.problem.import" => "向题库导入题目",
    "admin.problem.export" => "从题库中导出题目",
    "admin.contest.list" => "查看竞赛列表",
    "admin.contest.add" => "添加竞赛",
    "admin.contest.update" => "修改竞赛",
    "admin.contest.delete" => "删除竞赛",
    "admin.contest.delete_file" => "删除竞赛附件",
    "admin.contest.update_hidden" => "公开或隐藏竞赛",
    "admin.contest.clone" => "克隆竞赛",
    "admin.contest.update_order" => "改变竞赛的顺序",
    "admin.contest.update_contest_cate_id" => "修改竞赛所属的类别",
    "admin.contest.categories" => "查看竞赛类别列表",
    "admin.contest.update_cate" => "修改竞赛类别信息",
    "admin.contest.update_cate_order" => "改变竞赛类别的排列顺序",
    "admin.contest.delete_cate" => "删除竞赛类别",
    "admin.settings" => "修改系统设置",
    "admin.upgrade" => "查看系统版本信息和升级信息",
    "admin.upgrade_oj" => "执行系统升级命令"
];
